"""Mock order data for demo purposes."""

MOCK_ORDERS = [
    {
        "id": 1,
        "customer": "Acme Corp",
        "product": "Cloud Platform License",
        "quantity": 5,
        "price": 2500.00,
        "status": "completed",
        "created_at": "2026-03-15T10:30:00Z",
    },
    {
        "id": 2,
        "customer": "TechStart Inc",
        "product": "API Gateway",
        "quantity": 1,
        "price": 499.99,
        "status": "pending",
        "created_at": "2026-03-20T14:22:00Z",
    },
    {
        "id": 3,
        "customer": "DataFlow Systems",
        "product": "Database Cluster",
        "quantity": 3,
        "price": 1200.00,
        "status": "processing",
        "created_at": "2026-03-22T09:15:00Z",
    },
    {
        "id": 4,
        "customer": "GlobalTech Solutions",
        "product": "Kubernetes Enterprise",
        "quantity": 2,
        "price": 3500.00,
        "status": "completed",
        "created_at": "2026-03-25T11:00:00Z",
    },
    {
        "id": 5,
        "customer": "Nexus Digital",
        "product": "Cloud Platform License",
        "quantity": 10,
        "price": 2500.00,
        "status": "completed",
        "created_at": "2026-03-28T08:45:00Z",
    },
    {
        "id": 6,
        "customer": "Pinnacle AI",
        "product": "ML Pipeline Suite",
        "quantity": 1,
        "price": 4200.00,
        "status": "processing",
        "created_at": "2026-04-01T16:30:00Z",
    },
    {
        "id": 7,
        "customer": "SwiftLogistics",
        "product": "API Gateway",
        "quantity": 3,
        "price": 499.99,
        "status": "completed",
        "created_at": "2026-04-03T13:20:00Z",
    },
    {
        "id": 8,
        "customer": "Orion Healthcare",
        "product": "Database Cluster",
        "quantity": 1,
        "price": 1200.00,
        "status": "pending",
        "created_at": "2026-04-05T10:10:00Z",
    },
    {
        "id": 9,
        "customer": "Vertex Financial",
        "product": "Kubernetes Enterprise",
        "quantity": 5,
        "price": 3500.00,
        "status": "completed",
        "created_at": "2026-04-08T09:00:00Z",
    },
    {
        "id": 10,
        "customer": "Horizon Media",
        "product": "Cloud Platform License",
        "quantity": 2,
        "price": 2500.00,
        "status": "pending",
        "created_at": "2026-04-10T15:45:00Z",
    },
]
